In [ ]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores

In [ ]:
def abc(s):
    return s.max()
scores.apply(abc)

In [3]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

         國文      英文    數學     地理     歷史
最低分   50.00   51.00  51.0  50.00   53.0
最高分  100.00  100.00  98.0  98.00  100.0
平均    74.56   73.98  75.5  71.74   77.1

In [4]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

      國文   英文  數學  地理   歷史
1號    57   59  80  98   93
2號    77   92  83  78   81
3號    90   63  68  66   62
4號    90   72  89  96  100
5號    69   74  96  70   63
6號    52   76  89  91   85
7號    85   51  84  51   81
8號    68   84  77  56   78
9號    69   88  95  50   61
10號   73   94  83  74   69
11號   55   73  55  87   80
12號   52   51  83  68   83
13號   58   69  60  54   73
14號   90   81  74  72   94
15號   81   75  81  66   76
16號   81   72  85  71  100
17號   73   81  65  60   72
18號   91   78  91  87   63
19號   95   61  59  71   61
20號   83   55  76  98   70
21號   70   87  94  79   93
22號   66   69  75  56   86
23號   94   52  90  63   60
24號   51   89  76  82   73
25號   63   75  71  73  100
26號   67   99  72  86   80
27號   81   87  73  90   89
28號   81   62  69  93   57
29號   72   58  51  55   64
30號   88   90  60  77   62
31號   59   75  85  61   67
32號   50   64  63  64   82
33號   72   82  61  94   90
34號   86   84  58  72   56
35號   92   51  90  65   85
36號   59   93  92  60   80
37號   93   71  90  51   90
38號   75  100  87  79   73
39號   93   68  59  53   75
40號   83   82  55  73   70
41號   75   96  64  56   89
42號   54   60  96  71   63
43號   50   51  64  60   82
44號   58   63  54  50   71
45號  100   65  79  74   53
46號   83   69  81  55   87
47號   52  100  66  96   90
48號   89   59  75  79   90
49號   95   80  98  83   67
50號   88   69  54  73   86

In [5]:
def abc1(item):
    return pd.Series([item.sum(),item.mean()],index=['總分','平均'])
scores.apply(abc1,axis=1)

        總分    平均
1號   387.0  77.4
2號   411.0  82.2
3號   349.0  69.8
4號   447.0  89.4
5號   372.0  74.4
6號   393.0  78.6
7號   352.0  70.4
8號   363.0  72.6
9號   363.0  72.6
10號  393.0  78.6
11號  350.0  70.0
12號  337.0  67.4
13號  314.0  62.8
14號  411.0  82.2
15號  379.0  75.8
16號  409.0  81.8
17號  351.0  70.2
18號  410.0  82.0
19號  347.0  69.4
20號  382.0  76.4
21號  423.0  84.6
22號  352.0  70.4
23號  359.0  71.8
24號  371.0  74.2
25號  382.0  76.4
26號  404.0  80.8
27號  420.0  84.0
28號  362.0  72.4
29號  300.0  60.0
30號  377.0  75.4
31號  347.0  69.4
32號  323.0  64.6
33號  399.0  79.8
34號  356.0  71.2
35號  383.0  76.6
36號  384.0  76.8
37號  395.0  79.0
38號  414.0  82.8
39號  348.0  69.6
40號  363.0  72.6
41號  380.0  76.0
42號  344.0  68.8
43號  307.0  61.4
44號  296.0  59.2
45號  371.0  74.2
46號  375.0  75.0
47號  404.0  80.8
48號  392.0  78.4
49號  423.0  84.6
50號  370.0  74.0

In [9]:
one_student = scores.iloc[0]
less_student = one_student[one_student < 60]
less_student

國文    57
英文    59
Name: 1號, dtype: int32

In [10]:
less_student.count()
",".join(less_student.index.values.tolist())

'國文,英文'